services:
  - type: web
    name: edumanage
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn edumanage.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: edumanage.settings
      - key: PYTHON_VERSION
        value: 3.10
